In [1]:
import pandas as pd
import os

In [2]:
df = pd.read_csv("experiment_log.csv")
columns = {
    "deepseek-r1:latest": "DeepSeek-R1",
    "llama3.2:latest": "Llama3.2",
    "qwen2.5:latest": "Qwen2.5",
    "qwen3.5:latest": "Qwen3.5",
    "mistral": "Mistral",
    "assist2009": "ASSISTments 2009",
}
df["dataset_name"] = df["dataset_name"].apply(lambda x: columns[x])
df.rename(columns={"model_name": "Model", "dataset_name": "Dataset"}, inplace=True)
df

,Dataset,Model,trainauc,trainacc,validauc,validacc,testauc,testacc
0,Llama3.2,dkt,0.894802,0.868771,0.869210,0.855104,0.871442,0.854701
1,Mistral,dkt,0.884595,0.860516,0.876764,0.857985,0.867343,0.865052
2,Qwen3.5,dkt,0.888498,0.861953,0.895596,0.866511,0.869190,0.859907
3,Qwen2.5,dkt,0.882718,0.860844,0.860292,0.870810,0.876316,0.857752
4,DeepSeek-R1,dkt,0.885416,0.867389,0.897946,0.867511,0.872925,0.865039
5,ASSISTments 2009,dkt,0.865165,0.826422,0.798089,0.784864,0.794926,0.782129
6,Llama3.2,sakt,0.910440,0.882080,0.872203,0.862788,0.881908,0.864103
7,Mistral,sakt,0.898530,0.868651,0.888369,0.850913,0.871033,0.843714
8,Qwen3.5,sakt,0.900426,0.868013,0.891581,0.866511,0.882633,0.859239
9,Qwen2.5,sakt,0.900130,0.862837,0.870808,0.868017,0.880079,0.855619
10,DeepSeek-R1,sakt,0.893323,0.868410,0.898602,0.865823,0.882839,0.879820
11,ASSISTments 2009,sakt,0.843328,0.805354,0.653841,0.722693,0.666672,0.734738
12,Llama3.2,akt,0.883193,0.845559,0.874985,0.863886,0.867517,0.861538
13,Mistral,akt,0.879509,0.840675,0.884417,0.858574,0.870154,0.865052
14,Qwen3.5,akt,0.886606,0.846689,0.886112,0.866511,0.874426,0.859907
15,Qwen2.5,akt,0.877178,0.853415,0.862359,0.844274,0.869934,0.835704
16,DeepSeek-R1,akt,0.873320,0.863711,0.896214,0.860759,0.877138,0.859254
17,ASSISTments 2009,akt,0.852197,0.813949,0.790921,0.784635,0.785136,0.782852
18,Llama3.2,simplekt,0.994718,0.975859,0.954872,0.928650,0.955697,0.923932
19,Mistral,simplekt,0.907227,0.860714,0.899737,0.858574,0.883217,0.865052
20,Qwen3.5,simplekt,0.887927,0.865095,0.883173,0.852459,0.882271,0.855237
21,Qwen2.5,simplekt,0.880993,0.860120,0.859191,0.870810,0.870958,0.857752
22,DeepSeek-R1,simplekt,0.879043,0.863711,0.890060,0.856540,0.883619,0.872751
23,ASSISTments 2009,simplekt,0.912988,0.859499,0.750806,0.763797,0.746733,0.760242
24,Llama3.2,dtransformer,0.998329,0.983906,0.989159,0.973655,0.986619,0.980342
25,Mistral,dtransformer,0.998154,0.984921,0.996199,0.982322,0.992131,0.971165
26,Qwen3.5,dtransformer,0.997612,0.982941,0.992037,0.973458,0.994289,0.980654
27,Qwen2.5,dtransformer,0.997566,0.980975,0.992921,0.972067,0.995576,0.980085
28,DeepSeek-R1,dtransformer,0.997196,0.980997,0.990471,0.983122,0.993342,0.979434
29,ASSISTments 2009,dtransformer,0.932369,0.864998,0.770940,0.766888,0.772092,0.772814

In [3]:
df.sort_values(by=["Model", "Dataset"], inplace=True, ignore_index=True)
df

,Dataset,Model,trainauc,trainacc,validauc,validacc,testauc,testacc
0,ASSISTments 2009,akt,0.852197,0.813949,0.790921,0.784635,0.785136,0.782852
1,DeepSeek-R1,akt,0.873320,0.863711,0.896214,0.860759,0.877138,0.859254
2,Llama3.2,akt,0.883193,0.845559,0.874985,0.863886,0.867517,0.861538
3,Mistral,akt,0.879509,0.840675,0.884417,0.858574,0.870154,0.865052
4,Qwen2.5,akt,0.877178,0.853415,0.862359,0.844274,0.869934,0.835704
5,Qwen3.5,akt,0.886606,0.846689,0.886112,0.866511,0.874426,0.859907
6,ASSISTments 2009,dkt,0.865165,0.826422,0.798089,0.784864,0.794926,0.782129
7,DeepSeek-R1,dkt,0.885416,0.867389,0.897946,0.867511,0.872925,0.865039
8,Llama3.2,dkt,0.894802,0.868771,0.869210,0.855104,0.871442,0.854701
9,Mistral,dkt,0.884595,0.860516,0.876764,0.857985,0.867343,0.865052
10,Qwen2.5,dkt,0.882718,0.860844,0.860292,0.870810,0.876316,0.857752
11,Qwen3.5,dkt,0.888498,0.861953,0.895596,0.866511,0.869190,0.859907
12,ASSISTments 2009,dtransformer,0.932369,0.864998,0.770940,0.766888,0.772092,0.772814
13,DeepSeek-R1,dtransformer,0.997196,0.980997,0.990471,0.983122,0.993342,0.979434
14,Llama3.2,dtransformer,0.998329,0.983906,0.989159,0.973655,0.986619,0.980342
15,Mistral,dtransformer,0.998154,0.984921,0.996199,0.982322,0.992131,0.971165
16,Qwen2.5,dtransformer,0.997566,0.980975,0.992921,0.972067,0.995576,0.980085
17,Qwen3.5,dtransformer,0.997612,0.982941,0.992037,0.973458,0.994289,0.980654
18,ASSISTments 2009,sakt,0.843328,0.805354,0.653841,0.722693,0.666672,0.734738
19,DeepSeek-R1,sakt,0.893323,0.868410,0.898602,0.865823,0.882839,0.879820
20,Llama3.2,sakt,0.910440,0.882080,0.872203,0.862788,0.881908,0.864103
21,Mistral,sakt,0.898530,0.868651,0.888369,0.850913,0.871033,0.843714
22,Qwen2.5,sakt,0.900130,0.862837,0.870808,0.868017,0.880079,0.855619
23,Qwen3.5,sakt,0.900426,0.868013,0.891581,0.866511,0.882633,0.859239
24,ASSISTments 2009,simplekt,0.912988,0.859499,0.750806,0.763797,0.746733,0.760242
25,DeepSeek-R1,simplekt,0.879043,0.863711,0.890060,0.856540,0.883619,0.872751
26,Llama3.2,simplekt,0.994718,0.975859,0.954872,0.928650,0.955697,0.923932
27,Mistral,simplekt,0.907227,0.860714,0.899737,0.858574,0.883217,0.865052
28,Qwen2.5,simplekt,0.880993,0.860120,0.859191,0.870810,0.870958,0.857752
29,Qwen3.5,simplekt,0.887927,0.865095,0.883173,0.852459,0.882271,0.855237

In [4]:
def create_pivot_table(
    df: pd.DataFrame, value_column: str, table_name: str
) -> pd.DataFrame:
    pt = pd.pivot_table(
        df,
        values=value_column,
        index="Dataset",
        columns="Model",
        margins=True,
        margins_name="Average",
    )

    column_format = "+l^c^c^c^c^c^>{\\bfseries}^c"
    caption = f"{table_name} across LLM Synthesizers and Knowledge Tracing Models."
    label = f"\\label{{tab:{value_column}}}"

    pt_latex: str = pt.to_latex(
        float_format="%.4f",
        column_format=column_format,
        index_names=False,
        header=["AKT", "DKT", "DTransformer", "SAKT", "SimpleKT", "Average"],
        caption=caption + label,
        position="H",
    )
    kt_title = "&\\multicolumn{6}{c}{\\textbf{Knowledge Tracing Algorithms}}\\\\ \n"
    bold_rowstyle = "\\rowstyle{\\bfseries}"

    pt_latex = pt_latex.replace("\nModel", "\nSynthesizer")
    pt_latex = pt_latex.replace("[H]", "[H]\n\\centering")
    pt_latex = pt_latex.replace("DeepSeek-R1", "\\midrule\nDeepSeek-R1")
    pt_latex = pt_latex.replace("\\toprule", "\\toprule\n" + kt_title + bold_rowstyle)
    pt_latex = pt_latex.replace("\nAverage", f"\n\\midrule\n{bold_rowstyle}\nAverage")

    os.makedirs("tables", exist_ok=True)
    with open(f"../dissertation/tables/{value_column}.tex", "w") as f:
        f.write(pt_latex)

    return pt

In [5]:
pivot_table_names = {
    "trainacc": "Last epoch \\textbf{Train Accuracy}",
    "trainauc": "Last epoch \\textbf{Train AUC}",
    "validacc": "Last epoch \\textbf{Validation Accuracy}",
    "validauc": "Last epoch \\textbf{Validation AUC}",
    "testacc": "\\textbf{Test Accuracy}",
    "testauc": "\\textbf{Test AUC}",
}

tables = {}
for value, table_name in pivot_table_names.items():
    tables[value] = create_pivot_table(df, value, table_name)

In [6]:
print(abs(tables["trainauc"] - tables["validauc"]).mean().mean())
print(abs(tables["trainauc"] - tables["testauc"]).mean().mean())
print(abs(tables["trainacc"] - tables["validacc"]).mean().mean())
print(abs(tables["trainacc"] - tables["testacc"]).mean().mean())

print()

print(abs(tables["trainauc"] - tables["validauc"]).T.mean().mean())
print(abs(tables["trainauc"] - tables["testauc"]).T.mean().mean())
print(abs(tables["trainacc"] - tables["validacc"]).T.mean().mean())
print(abs(tables["trainacc"] - tables["testacc"]).T.mean().mean())

0.03165043501194414
0.032577758242528024
0.018702932919535526
0.01884478714276637

0.03165043501194414
0.032577758242528024
0.018702932919535526
0.018844787142766373

In [7]:
pd.set_option("display.width", 88)
pd.set_option("display.max_columns", None)

print("trainauc - validauc")
print(abs(tables["trainauc"] - tables["validauc"]))
print()

print("trainauc - testauc")
print(abs(tables["trainauc"] - tables["testauc"]))
print()

print("trainacc - validacc")
print(abs(tables["trainacc"] - tables["validacc"]))
print()

print("trainacc - testacc")
print(abs(tables["trainacc"] - tables["testacc"]))

trainauc - validauc
Model                  akt       dkt  dtransformer      sakt  simplekt   Average
Dataset
ASSISTments 2009  0.061276  0.067076      0.161428  0.189488  0.162182  0.128290
DeepSeek-R1       0.022894  0.012530      0.006724  0.005279  0.011016  0.008999
Llama3.2          0.008208  0.025592      0.009170  0.038237  0.039847  0.024211
Mistral           0.004908  0.007831      0.001954  0.010161  0.007490  0.004506
Qwen2.5           0.014818  0.022426      0.004645  0.029323  0.021802  0.018603
Qwen3.5           0.000493  0.007098      0.005575  0.008845  0.004754  0.002514
Average           0.009499  0.017216      0.031583  0.045129  0.037510  0.028187

trainauc - testauc
Model                  akt       dkt  dtransformer      sakt  simplekt   Average
Dataset
ASSISTments 2009  0.067061  0.070239      0.160277  0.176656  0.166255  0.128098
DeepSeek-R1       0.003818  0.012491      0.003853  0.010484  0.004576  0.003687
Llama3.2          0.015676  0.023360      0.011709  0.028532  0.039021  0.023660
Mistral           0.009355  0.017252      0.006023  0.027497  0.024011  0.016828
Qwen2.5           0.007244  0.006402      0.001990  0.020052  0.010035  0.009145
Qwen3.5           0.012179  0.019308      0.003324  0.017793  0.005656  0.011652
Average           0.017950  0.024842      0.031196  0.046836  0.040067  0.032178

trainacc - validacc
Model                  akt       dkt  dtransformer      sakt  simplekt   Average
Dataset
ASSISTments 2009  0.029314  0.041558      0.098110  0.082661  0.095703  0.069469
DeepSeek-R1       0.002951  0.000122      0.002125  0.002588  0.007171  0.002092
Llama3.2          0.018327  0.013667      0.010251  0.019292  0.047209  0.014418
Mistral           0.017899  0.002531      0.002599  0.017737  0.002140  0.001422
Qwen2.5           0.009142  0.009966      0.008908  0.005179  0.010690  0.001557
Qwen3.5           0.019821  0.004558      0.009482  0.001503  0.012636  0.000152
Average           0.002440  0.007185      0.021204  0.019767  0.025695  0.014282

trainacc - testacc
Model                  akt       dkt  dtransformer      sakt  simplekt   Average
Dataset
ASSISTments 2009  0.031096  0.044293      0.092184  0.070616  0.099257  0.067489
DeepSeek-R1       0.004456  0.002350      0.001563  0.011410  0.009040  0.002416
Llama3.2          0.015980  0.014070      0.003564  0.017977  0.051927  0.014312
Mistral           0.024377  0.004536      0.013756  0.024937  0.004338  0.001088
Qwen2.5           0.017711  0.003092      0.000889  0.007219  0.002367  0.006256
Qwen3.5           0.013217  0.002046      0.002287  0.008774  0.009859  0.001950
Average           0.000052  0.010219      0.019040  0.019685  0.025005  0.014780

In [8]:
print(abs(tables["testacc"] - tables["trainacc"]).T.mean())

Dataset
ASSISTments 2009    0.067489
DeepSeek-R1         0.005206
Llama3.2            0.019638
Mistral             0.012172
Qwen2.5             0.006256
Qwen3.5             0.006355
Average             0.014797
dtype: float64